apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=
# Create secret before deployment
# echo -n "username" | base64
# echo -n "password" | base64
# Converted the known username and password to special texts
# metadata name is to call this secret to deployment file 